# Generated by Django 4.0.3 on 2022-04-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasky_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30, unique=True)),
                ('order', models.IntegerField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='stage',
        ),
    ]
