# Generated by Django 4.0.3 on 2022-04-06 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasky_api', '0002_stage_remove_task_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='Title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='stage',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasky_api.task'),
        ),
    ]
