# Generated by Django 4.0.3 on 2022-04-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasky_api', '0002_project_stage_task_project_alter_task_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
