# Generated by Django 4.0.3 on 2022-04-12 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasky_api', '0003_alter_stage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='projects',
        ),
        migrations.AddField(
            model_name='stage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasky_api.project'),
        ),
    ]
