# Generated by Django 4.0.3 on 2022-04-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasky_api', '0005_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='projects',
            field=models.ManyToManyField(blank=True, to='tasky_api.project'),
        ),
    ]
